In [1]:
import numpy as np 
import pandas as pd 


In [2]:
import os
print(os.listdir("dataset"))

['.DS_Store', 'dataset.json']


In [3]:
df = pd.read_json('dataset/dataset.json', lines= True)


In [4]:
df.head(25)

content  \
0                              Get fucking real dude.   
1    She is as dirty as they come  and that crook ...   
2    why did you fuck it up. I could do it all day...   
3    Dude they dont finish enclosing the fucking s...   
4    WTF are you talking about Men? No men thats n...   
5   Ill save you the trouble sister. Here comes a ...   
6    Im dead serious.Real athletes never cheat don...   
7   ...go absolutely insane.hate to be the bearer ...   
8   Lmao  im watching the same thing ahaha. The ga...   
9   LOL  no he said  What do you call a jail cell ...   
10  truth on both counts that guy is an ass  and t...   
11                                  Shakespeare nerd!   
12                        you are SUCH a fucking dork   
13                             Heh. Fuck 'em WHERE?!?   
14                 damn it i totally forgot that one!   
15       wow  damn I would have been pissed @ that...   
16      nigga u geigh lmao! fuck yo finals beeeeeitch   
17                                      that sucks :(   
18  read that this morning. my fav is how they jus...   
19        Unibroue 17 !!!! Another damn good Unibroue   
20  damn your evil 60 minute IPA beckoning me from...   
21  It did  then my fucking dad turned it off. I j...   
22                it pretty much is a fuck you card..   
23                         that karma is a bitch  HUH   
24     don't get too fat or you'll turn into a boomer   

                       annotation  extras  
0   {'notes': '', 'label': ['1']}     NaN  
1   {'notes': '', 'label': ['1']}     NaN  
2   {'notes': '', 'label': ['1']}     NaN  
3   {'notes': '', 'label': ['1']}     NaN  
4   {'notes': '', 'label': ['1']}     NaN  
5   {'notes': '', 'label': ['1']}     NaN  
6   {'notes': '', 'label': ['1']}     NaN  
7   {'notes': '', 'label': ['1']}     NaN  
8   {'notes': '', 'label': ['1']}     NaN  
9   {'notes': '', 'label': ['1']}     NaN  
10  {'notes': '', 'label': ['1']}     NaN  
11  {'notes': '', 'label': ['1']}     NaN  
12  {'notes': '', 'label': ['1']}     NaN  
13  {'notes': '', 'label': ['1']}     NaN  
14  {'notes': '', 'label': ['1']}     NaN  
15  {'notes': '', 'label': ['1']}     NaN  
16  {'notes': '', 'label': ['1']}     NaN  
17  {'notes': '', 'label': ['1']}     NaN  
18  {'notes': '', 'label': ['1']}     NaN  
19  {'notes': '', 'label': ['1']}     NaN  
20  {'notes': '', 'label': ['1']}     NaN  
21  {'notes': '', 'label': ['1']}     NaN  
22  {'notes': '', 'label': ['1']}     NaN  
23  {'notes': '', 'label': ['1']}     NaN  
24  {'notes': '', 'label': ['1']}     NaN

In [5]:
df.tail(25)

content  \
19976        Do you wish someone was with you right now?   
19977                                   kohl's actually.   
19978    yes. but we end up warped in the end either ...   
19979                           Entertainingly cheesy :]   
19980          Do you think you&apos;re hot and/or sexy?   
19981                                            repeat.   
19982    I cannot listen to that Heavy metal! I like ...   
19983          DO U NO ALIX&;S SISTER HAS A CRUCH ON YOU   
19984                                             repeat   
19985                                       hey who diz?   
19986   I aint da one dat said da tampon thang. But i...   
19987                   How many languages do you speak?   
19988                             lol no iDnt iGuess bih   
19989    sometimes. i did that a lot when i was sick ...   
19990                              You'll neverr know (:   
19991                                   hold im confused   
19992                               i wouldnt catch one.   
19993    Haha nahh ive just fractured some thumbs bhu...   
19994        did we have any classes together this year?   
19995                 I Havent Gotten 2 that part!! haha   
19996    I dont. But what is complaining about it goi...   
19997   Bahah  yeah i&;m totally just gonna&; get pis...   
19998       hahahahaha >:) im evil mwahahahahahahahahaha   
19999            What&;s something unique about Ohio? :)   
20000              Who is the biggest gossiper you know?   

                          annotation  extras  
19976  {'notes': '', 'label': ['0']}     NaN  
19977  {'notes': '', 'label': ['0']}     NaN  
19978  {'notes': '', 'label': ['0']}     NaN  
19979  {'notes': '', 'label': ['0']}     NaN  
19980  {'notes': '', 'label': ['0']}     NaN  
19981  {'notes': '', 'label': ['0']}     NaN  
19982  {'notes': '', 'label': ['0']}     NaN  
19983  {'notes': '', 'label': ['0']}     NaN  
19984  {'notes': '', 'label': ['0']}     NaN  
19985  {'notes': '', 'label': ['0']}     NaN  
19986  {'notes': '', 'label': ['0']}     NaN  
19987  {'notes': '', 'label': ['0']}     NaN  
19988  {'notes': '', 'label': ['0']}     NaN  
19989  {'notes': '', 'label': ['0']}     NaN  
19990  {'notes': '', 'label': ['0']}     NaN  
19991  {'notes': '', 'label': ['0']}     NaN  
19992  {'notes': '', 'label': ['0']}     NaN  
19993  {'notes': '', 'label': ['0']}     NaN  
19994  {'notes': '', 'label': ['0']}     NaN  
19995  {'notes': '', 'label': ['0']}     NaN  
19996  {'notes': '', 'label': ['0']}     NaN  
19997  {'notes': '', 'label': ['0']}     NaN  
19998  {'notes': '', 'label': ['0']}     NaN  
19999  {'notes': '', 'label': ['0']}     NaN  
20000  {'notes': '', 'label': ['0']}     NaN

In [6]:
df.shape

(20001, 3)

In [7]:
df["label"] = df.annotation.apply(lambda x: x.get('label'))
df["label"] = df.label.apply(lambda x: x[0])

df.head()

content  \
0                             Get fucking real dude.   
1   She is as dirty as they come  and that crook ...   
2   why did you fuck it up. I could do it all day...   
3   Dude they dont finish enclosing the fucking s...   
4   WTF are you talking about Men? No men thats n...   

                      annotation  extras label  
0  {'notes': '', 'label': ['1']}     NaN     1  
1  {'notes': '', 'label': ['1']}     NaN     1  
2  {'notes': '', 'label': ['1']}     NaN     1  
3  {'notes': '', 'label': ['1']}     NaN     1  
4  {'notes': '', 'label': ['1']}     NaN     1

In [8]:
df.extras.unique()

array([nan])

In [9]:
df["notes"] = df.annotation.apply(lambda x: x.get('notes'))
df.notes.unique()

array([''], dtype=object)

In [10]:
import nltk
nltk.download(['punkt', 'wordnet'])

import re
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [11]:
def load_data(path):
    df = pd.read_json(path, lines= True)
    
    df["label"] = df.annotation.apply(lambda x: x.get('label'))
    df["label"] = df.label.apply(lambda x: x[0])
    
    X = df.content.values
    y = df.label.values
    
    return X, y

def tokenize(text):

    tokens = word_tokenize(text)
    lemmatizer = WordNetLemmatizer()

    clean_tokens = []
    for tok in tokens:
        clean_tok = lemmatizer.lemmatize(tok).lower().strip()
        clean_tokens.append(clean_tok)

    return clean_tokens

def display_results(y_test, y_pred):
    labels = np.unique(y_pred)
    confusion_mat = confusion_matrix(y_test, y_pred, labels=labels)
    accuracy = (y_pred == y_test).mean()

    print("Labels:", labels)
    print("Confusion Matrix:\n", confusion_mat)
    print("Accuracy:", accuracy)
    
def main():
    url = 'dataset/dataset.json'
    X, y = load_data(url)
    X_train, X_test, y_train, y_test = train_test_split(X, y)
    print ("X_train: ", len(X_train))
    print("X_test: ", len(X_test))
    print("y_train: ", len(y_train))
    print("y_test: ", len(y_test))

    vect = CountVectorizer(tokenizer=tokenize)
    tfidf = TfidfTransformer()
    clf = RandomForestClassifier()
    
    # train classifier
    X_train_counts = vect.fit_transform(X_train)
    X_train_tfidf = tfidf.fit_transform(X_train_counts)
    clf.fit(X_train_tfidf, y_train)

    # predict on test data
    X_test_counts = vect.transform(X_test)
    X_test_tfidf = tfidf.transform(X_test_counts)
    y_pred = clf.predict(X_test_tfidf)
    
    # predict on test data
    X_test_counts = vect.transform(["whoa stop you stupid sjw"])
    X_test_tfidf = tfidf.transform(X_test_counts)
    print("Given text: 'whoa stop you stupid sjw' ")
    print("Prediction: {}\n".format(clf.predict(X_test_tfidf)))
    print("Random Forest")

    # display results
    display_results(y_test, y_pred)
    
    mnb = MultinomialNB()
    
    # train classifier
    X_train_counts = vect.fit_transform(X_train)
    X_train_tfidf = tfidf.fit_transform(X_train_counts)
    mnb.fit(X_train_tfidf, y_train)

    # predict on test data
    X_test_counts = vect.transform(X_test)
    X_test_tfidf = tfidf.transform(X_test_counts)
    y_pred = mnb.predict(X_test_tfidf)
    
    # predict on test data
    X_test_counts = vect.transform(["whoa stop you stupid sjw"])
    X_test_tfidf = tfidf.transform(X_test_counts)
    print("Given text: 'whoa stop you stupid sjw' ")
    print("Prediction: {}\n".format(clf.predict(X_test_tfidf)))
    print("MultinomialNB")
    

    # display results
    display_results(y_test, y_pred)
    
    dtc = DecisionTreeClassifier()
    
    # train classifier
    X_train_counts = vect.fit_transform(X_train)
    X_train_tfidf = tfidf.fit_transform(X_train_counts)
    dtc.fit(X_train_tfidf, y_train)

    # predict on test data
    X_test_counts = vect.transform(X_test)
    X_test_tfidf = tfidf.transform(X_test_counts)
    y_pred = dtc.predict(X_test_tfidf)
    
    # predict on test data
    X_test_counts = vect.transform(["whoa stop you stupid sjw"])
    X_test_tfidf = tfidf.transform(X_test_counts)
    print("Given text: 'whoa stop you stupid sjw' ")
    print("Prediction: {}\n".format(clf.predict(X_test_tfidf)))
    print("Decision Tree")
    

    # display results
    display_results(y_test, y_pred)
    
    svm = SVC()

    # train classifier
    X_train_counts = vect.fit_transform(X_train)
    X_train_tfidf = tfidf.fit_transform(X_train_counts)
    svm.fit(X_train_tfidf, y_train)

    # predict on test data
    X_test_counts = vect.transform(X_test)
    X_test_tfidf = tfidf.transform(X_test_counts)
    y_pred = svm.predict(X_test_tfidf)
    
    # predict on test data
    X_test_counts = vect.transform(["whoa stop you stupid sjw"])
    X_test_tfidf = tfidf.transform(X_test_counts)
    print("Given text: 'whoa stop you stupid sjw' ")
    print("Prediction: {}\n".format(clf.predict(X_test_tfidf)))
    print("Support Vector Machine")

    # display results
    display_results(y_test, y_pred)


main()

X_train:  15000
X_test:  5001
y_train:  15000
y_test:  5001
Given text: 'whoa stop you stupid sjw' 
Prediction: ['1']

Random Forest
Labels: ['0' '1']
Confusion Matrix:
 [[2961  118]
 [ 170 1752]]
Accuracy: 0.9424115176964607
Given text: 'whoa stop you stupid sjw' 
Prediction: ['1']

MultinomialNB
Labels: ['0' '1']
Confusion Matrix:
 [[2921  158]
 [ 955  967]]
Accuracy: 0.7774445110977805
Given text: 'whoa stop you stupid sjw' 
Prediction: ['1']

Decision Tree
Labels: ['0' '1']
Confusion Matrix:
 [[2499  580]
 [ 122 1800]]
Accuracy: 0.859628074385123
Given text: 'whoa stop you stupid sjw' 
Prediction: ['1']

Support Vector Machine
Labels: ['0' '1']
Confusion Matrix:
 [[2837  242]
 [ 244 1678]]
Accuracy: 0.9028194361127775
